# Generated by Django 5.1 on 2024-08-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image_url",
            field=models.ImageField(null=True, upload_to="media/category/"),
        ),
    ]
