# Generated by Django 5.1 on 2024-08-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_category_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image_url",
            field=models.ImageField(upload_to="media/category/"),
        ),
    ]
